API/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from API import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.info, name='info'),
    url(r'^core/$', views.core, name='core'),
    url(r'^core/dau/$', views.dau, name='dau'),
    url(r'^remote/$', views.remote, name='rm'),
]

Tricle/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Tricle import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^scrambler/', include('scrambler.urls', namespace='scrambler')),
    url(r'^scrambler/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^privacy$', views.PrivacyPage.as_view(), name='privacy'),
    url(r'contact/$', views.ContactPage.as_view(), name='contact'),
    url(r'global/$', views.stats, name='global'),
    url(r'go/$', views.GettingStarted.as_view(), name='go'),
    url(r'about/$', views.AboutPage.as_view(), name='about'),
    url(r'^scrambler/$', views.ScramRedirect),
    url(r'^iaw/$', views.cleanup, name="cleanup"),
    url(r'^api/', include('API.urls', namespace='api')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^thanks/$', views.ThanksPage, name='thanks'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
]

scrambler/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from scrambler import views

app_name = 'scrambler'

urlpatterns = [
    url(r'^$', views.StartPage, name='start'),
    url(r'^account/$', views.AccountPage, name='account'),
    url(r'^(?P<hash>\w+)/$', views.load_url, name="url"),
    url(r'^down/(?P<hash>\w+)/$', views.download_url, name="down"),
    url(r'^done/(?P<hash>\w+)/$', views.done_url, name="done"),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

scrambler/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.conf import settings

from datetime import datetime
from hashlib import sha1
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    scramble_count = models.IntegerField(default=0)
    unscramble_count = models.IntegerField(default=0)
    total_size_of_uploaded_images = models.BigIntegerField(default=0)
    total_file_count = models.IntegerField(default=0)
    last_login = models.DateTimeField(default=timezone.now, null=True)
    flagged = models.BooleanField(default=False)
    test_user = models.BooleanField(default=False)
    userkey = models.CharField(default=0, max_length=255)

    api_scrams = models.IntegerField(default=0)
    api_unscrams = models.IntegerField(default=0)
    api_requests = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def userkey_gen(self):
        username = self.user.username

        user_hash = username.encode("UTF-8")
        user_hash = sha1(user_hash).hexdigest()[:20]

        self.userkey = user_hash
        self.save()
        return self.userkey

class ExpiringURL(models.Model):
    url = models.CharField(default=0, max_length=255, unique=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    expired = models.BooleanField(default=False)
    number_of_files = models.IntegerField(default=0)
    user_name = models.CharField(default=0, max_length=255)
    mode = models.CharField(default="Scramble", max_length=255)
    down_count = models.IntegerField(default=0)

    def __str__(self):
        return self.url

class ExpiredURL(models.Model):
    url = models.CharField(default=0, max_length=255, unique=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    number_of_files = models.IntegerField(default=0)
    user_name = models.CharField(default=0, max_length=255)
    mode = models.CharField(default="Scramble", max_length=255)

    def __str__(self):
        return self.url



'''
make notification model
'''

'''
class Notification(models.Model):
    message = models.CharField(default=0, max_length=255)
    start date = datetime models
    duration = timedelta
'''

class DailyLedger(models.Model):
    date = models.DateTimeField(default=0, unique=True)
    dau = models.IntegerField(default=0)
    interaction_count = models.IntegerField(default=0)
    scram_count = models.IntegerField(default=0)
    unscram_count = models.IntegerField(default=0)
    total_files = models.IntegerField(default=0)
    login_count = models.IntegerField(default=0)

    api_requests = models.IntegerField(default=0)
    api_scrams = models.IntegerField(default=0)
    api_unscrams = models.IntegerField(default=0)

    def __str__(self):
        return self.date.strftime("%B %d, %Y")

class RemoteToken(models.Model):
    user_name = models.CharField(default=0, max_length=255)
    token = models.CharField(default=0, max_length=255)
    uses = models.IntegerField(default=0)

    def __str__(self):
        return self.token

    def increment_uses(self):
        if self.uses < settings.API_TOKEN_LIMIT:
            self.uses += 1
            self.save()
            return True
        else:
            self.expire()
            return False

    def expire(self):
        exptoken, check = ExpiredToken.objects.get_or_create(user_name=self.user_name, token=self.token)
        newtoken, check = RemoteToken.objects.get_or_create(user_name=self.user_name)
        newtoken.create_token()
        self.delete()
        return True

    def create_token(self):
        user = str(self.user_name)
        time = str(datetime.now().isoformat())
        hashkey = (user + time).encode("UTF-8")

        userhash = user.encode("UTF-8")
        userhash = sha1(userhash).hexdigest()[:5]

        otherhash = sha1(hashkey).hexdigest()[:15]

        self.token = str(otherhash) + str(userhash)[::-1]
        self.save()
        return self.token

class ExpiredToken(models.Model):
    user_name = models.CharField(default=0, max_length=255)
    token = models.CharField(default=0, max_length=255)

    def __str__(self):
        return self.token

    def propagate(self, user, token):
        self.user_name = user
        self.token = token
        self.save()

class RemoteInteraction(models.Model):
    rm_id = models.CharField(default=0, max_length=255, unique=True)
    user_name = models.CharField(default=0, max_length=255)
    created = models.DateTimeField(default=timezone.now, null=True)
    mode = models.CharField(default="Scramble", max_length=255)

    def __str__(self):
        return self.rm_id

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

scrambler/forms.py
from django import forms
from django.contrib.auth.models import User

class ScrambleForm(forms.Form):
    key_one = forms.CharField(label='', max_length=256, widget=forms.TextInput(attrs={'placeholder': 'Enter your first key'}))
    key_two = forms.CharField(label='', max_length=256, widget=forms.TextInput(attrs={'placeholder': 'Enter your second key'}))
    key_three = forms.CharField(label='', max_length=256, widget=forms.TextInput(attrs={'placeholder': 'Enter your third key'}))

    CHOICES=[('Scramble','Scramble'), ('Unscramble','Unscramble')]
    mode = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={'class':'regDropDown'}))

    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True,}))

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect

from accounts import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

def ThanksPage(request):
    #if not request.user.is_authenticated():
    #    return HttpResponseRedirect('/')
    template_name = 'accounts/thanks.html'
    return render(request, template_name)

def validate_username(request):
    username = request.GET.get('username', None)
    if username == None:
        return HttpResponse("Sneaky")
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

def validate_email(request):
    email = request.GET.get('email', None)
    if email == None:
        return HttpResponse("Sneaky")
    data = {
        'is_taken': User.objects.filter(email__iexact=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this email already exists.'
    return JsonResponse(data)

scrambler/templates/scrambler/account.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-user fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}

{% block content_block  %}
{% if user.is_authenticated %}
<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
      <h1 style="font-weight: lighter;">
      hey, {{ user.username }}
    </h1>
  </div>
</div>
{% endif %}

<div class="container">
  <div class="jumbotron">

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Username:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    {{ user.username}}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Email Address:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    {{ user.email }}
  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
        Number of images scrambled:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ user.profile.scramble_count }}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Number of images unscrambled:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ user.profile.unscramble_count }}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Number of bytes uploaded:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ n_o_b_u }}
  </div>
</div>



<hr>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    User API key:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ userkey }}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Token:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ token}}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Remaining uses:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ remain }}
  </div>
</div>

<div class="row">
  <div class="col-xs-12" style="margin-top:10px; margin-bottom:10px;">
    <a href="{% url 'api:info' %}">More about our API</a>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    Total API requests:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ api_requests }}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    API Scrambles:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ api_scrambles }}
  </div>
</div>

<div class="row">
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
    API Unscrambles:
  </div>
  <div class="col-xs-6" style="margin-top:10px; margin-bottom:10px;">
  {{ api_unscrambles }}
  </div>
</div>

<br>

<div class="row">
  <div class="col-xs-12" style="margin-top:10px; margin-bottom:10px;">
    <button type="button" class="btn btn-primary btn-block btn-lg" name="button">Change Account Details</button>
  </div>
</div>

<br>

</div>
</div>



{% endblock %}

scrambler/templates/scrambler/download.html
{% extends 'base.html' %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-download fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}


{% block content_block %}

<div id="jsal1" class="container">
  <div  class="alert alert-danger">
    As JavaScript is disabled, after ".xyz", put /scrambler/{{dl_url}}
  </div>
</div>

<div id="jsal2" class="container">
  <div class="alert alert-danger">
    Then, once you see some text appear, change it to /scrambler/down/{{dl_url}}
  </div>
</div>

<div id="jsal3" class="container">
  <div class="alert alert-danger">
    After you have downloaded your file, change it to /scrambler/done/{{dl_url}}
  </div>
</div>

<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
  <h3 id="note">Please wait while we prepare your download</h3>
  <!--<h3> {{ dl_url }}</h3>-->
  </div>
</div>

<div class="container">
  <div class="jumbotron">
      <button type="button" id="downdis" class="btn btn-lg btn-primary btn-block disabled" name="button"><i class="fa fa-cog fa-2x slow-spin fa-spin"></i></button>

    <a id="downen_link" style="display: none;" href="{% url 'scrambler:down' hash=dl_url %}" style="font-decoration: none;">
    <button type="button" id="downen" class="btn btn-lg btn-success btn-block enabled" name="button" style="border-bottom-left-radius: 0px; border-bottom-right-radius:0px;">
            <i class="fa fa-arrow-circle-o-down fa-2x"></i>
    </button>
    <div class="" style="background-color: #a1f4a1; padding: 10px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; color: #FFFFFA; border-top: 0px;">


    <strong>Click here</strong> if the download doesn't automatically start
      </div>
  </a>

  <br>

  <a id="done_link" style="display: none;" href="{% url 'scrambler:done' hash=dl_url %}" style="font-decoration: none;">
  <button type="button" id="done" class="btn btn-lg btn-primary btn-block enabled" name="button"  style="border-bottom-left-radius: 0px; border-bottom-right-radius:0px;">

        <i class="fa fa-check-circle-o fa-2x"></i>
      </button>

        <div class="" style="background-color: #7ac1ff; padding: 10px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px; color: #FFFFFA; border-top: 0px;">
              <strong>Downloaded?</strong> Click here to clear your files from the server
          </div>
</a>
  </div>
</div>

<div class="container" style="display:none;">
  <div class="jumbotron">
    <a id="runProc" href='{% url 'scrambler:url' hash=dl_url %}'>
    <button  type="button" name="button">Click to run process</button>
    </a>
  </div>
</div>

<div class="container" style="display: none;">
  <div class="jumbotron">
    <a href="{% url 'scrambler:down' hash=dl_url %}">
    <button id="downProc" type="button"  name="button">Click to download</button>
    </a>
    </div>
</div>

{% endblock %}

{% block js_block %}
<script type="text/javascript">
    $( document ).ready(function() {
      $.ajax({
        url: $('#runProc').attr("href"),
        dataType: 'json',
        success: function (data) {
          if (data.proc) {
            $('#note').text("Your download is ready");
            $('#downdis').css("display", "none");
            $('#downen_link').css("display", "block");
            $('#done_link').css("display", "block");

            $('#downen_link')[0].click();

            }
        else {
          }
        }
    });
  });
</script>

<script type="text/javascript">
  $('#jsal1').css("display", "none");
    $('#jsal2').css("display", "none");
      $('#jsal3').css("display", "none");
</script>
{% endblock %}

scrambler/templates/scrambler/start.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block head_block %}
<style type="text/css">
label
{
  display:none;
}

</style>
{% endblock %}


{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-play fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}

{% block content_block  %}

<div class="container">
  <a href="{% url 'go' %}" target="_blank">
    <div class="alert alert-info">
    <strong>Click here</strong> to figure out how to get started.
  </div>
  </a>

  <div class="alert alert-danger">
  <strong>Avoid</strong> using large pictures (greater than 1500x1500) as the scrambled image can be up to 50 times larger than the original, resulting in a large download for you.
</div>
</div>




<div class="container">
  <div class="jumbotron">


<div class="container">

<form enctype="multipart/form-data" method="POST">
        {% csrf_token %}

        <div class="form-group"><input type="text" name="key_one" maxlength="256" class="form-control" title="" required placeholder="Enter your first key" id="id_key_one" /></div>
        <div class="form-group"><input type="text" name="key_two" maxlength="256" class="form-control" title="" required placeholder="Enter your second key" id="id_key_two" /></div>
        <div class="form-group"><input type="text" name="key_three" maxlength="256" class="form-control" title="" required placeholder="Enter your third key" id="id_key_three" /></div>
        <div class="form-group"><label class="control-label" for="id_mode">Mode</label>
          <select name="mode" id="id_mode" class="form-control regDropDown" title="">
          <option value="Scramble">Scramble</option>
          <option value="Unscramble">Unscramble</option>
          </select>
        </div>
        <div style="margin-top: 0px; margin-bottom:20px;">

        <div class="input-group">
                <label class="input-group-btn">
                    <span class="btn btn-primary">
                        Browse&hellip; <input type="file" accept="image/*" style="display: none;" name="images" class="" title="" required multiple id="id_images">
                    </span>
                </label>
                <input type="text" class="form-control" readonly>
            </div>

          </div>

        <input class="btn btn-success btn-block btn-lg" type="submit" name="" value="Start">
      </form>

</div>
</div>
</div>

{% endblock %}

{% block js_block %}

<script type="text/javascript">
$(function() {

  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });

});
</script>

<script>
$(document).ready(function () {
$('input[type=file]').change(function () {
var val = $(this).val().toLowerCase();
var regex = new RegExp("(.*?)\.(jpeg|bmp|jpg)$");
 if(!(regex.test(val))) {
$(this).val('');
alert('Please select correct file format');
} }); });
</script>

{% endblock %}