API/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from API import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.info, name='info'),
    url(r'^core/$', views.core, name='core'),
    url(r'^core/dau/$', views.dau, name='dau'),
    url(r'^remote/$', views.remote, name='rm'),
]

Tricle/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Tricle import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^scrambler/', include('scrambler.urls', namespace='scrambler')),
    url(r'^scrambler/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^privacy$', views.PrivacyPage.as_view(), name='privacy'),
    url(r'contact/$', views.ContactPage.as_view(), name='contact'),
    url(r'global/$', views.stats, name='global'),
    url(r'go/$', views.GettingStarted.as_view(), name='go'),
    url(r'about/$', views.AboutPage.as_view(), name='about'),
    url(r'^scrambler/$', views.ScramRedirect),
    url(r'^iaw/$', views.cleanup, name="cleanup"),
    url(r'^api/', include('API.urls', namespace='api')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^thanks/$', views.ThanksPage, name='thanks'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.

class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect

from accounts import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

def ThanksPage(request):
    #if not request.user.is_authenticated():
    #    return HttpResponseRedirect('/')
    template_name = 'accounts/thanks.html'
    return render(request, template_name)

def validate_username(request):
    username = request.GET.get('username', None)
    if username == None:
        return HttpResponse("Sneaky")
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

def validate_email(request):
    email = request.GET.get('email', None)
    if email == None:
        return HttpResponse("Sneaky")
    data = {
        'is_taken': User.objects.filter(email__iexact=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this email already exists.'
    return JsonResponse(data)

accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block icon_block %}
<h1 style="text-align: center;"><i class="fa fa-pencil fa-2x" aria-hidden="true"></i></h1>
{% endblock %}

{% block content_block  %}
<div class="container">
  <div class="jumbotron">
    <div class="container" id="form_area">

  <form id="formdata" method="post"  data-userIsVal = "null" data-emailIsVal = "null" data-validate-username-url="{% url 'accounts:validate_username' %}" data-validate-email-url="{% url 'accounts:validate_email' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input id="CA_button" type="submit" name="" value="Create Account" class="btn btn-success btn-block btn-lg">
  </form>
  <button id="CA_doppleganger" style="display: none;" type="button" class="btn btn-success btn-lg btn-block" name="button">Create Account</button>
</div>
</div>

</div>
{% endblock %}


{% block head_block %}
<style type="text/css">
label
{
  display:none;
}


.help-block {
  display:none;
}
</style>
{% endblock %}



{% block js_block %}

<script type="text/javascript">
  $("#id_username").change(function () {
    var form = $(this).closest("form");
    $.ajax({
      url: form.attr("data-validate-username-url"),
      data: form.serialize(),
      dataType: 'json',
      success: function (data) {
        if (data.is_taken) {
          $("#id_username").val("");
          $("#id_username").attr("placeholder", "That username is taken");
          $("#id_username").css("border-color", "#ff6666");
          $("#id_username").focus();
          $("#formdata").data("userIsVal", "0");
          }
        else {
          $("#id_username").css("border-color", "#66ff99");
          $("#formdata").data("userIsVal", "1");
          }
        }
      });
    });
  </script>

<script type="text/javascript">
    $("#id_email").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-email-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            $("#id_email").val("");
            $("#id_email").attr("placeholder", "That email address is taken");
            $("#id_email").css("border-color", "#ff6666");
            $("#id_email").focus();
            $("#formdata").data("emailIsVal", "0");
            }
        else {
          $("#id_email").css("border-color", "#66ff99");
          $("#formdata").data("emailIsVal", "1");
          }
        }
    });
  });
</script>


<script type="text/javascript">
  $("#CA_button").css("display", "none");
  $("#CA_doppleganger").css("display", "block");
</script>

<script type="text/javascript">
    $("#CA_doppleganger").on('click', function() {
      var delay=2000; //1 second
      var min_pass_len = 6;
      var ps1 = document.getElementById("id_password1").value;
      var ps2 = document.getElementById("id_password2").value;

      if (ps1 != ps2){
      setTimeout(function() {
                  $("#CA_doppleganger").text("Create Account");
                  $("#CA_doppleganger").css("border-color", "#4cae4c");
                  $("#CA_doppleganger").css("background-color", "#5cb85c");
      }, delay);
      $('#CA_doppleganger').text("Passwords don't match");
      $("#CA_doppleganger").css("border-color", "#eea236");
      $("#CA_doppleganger").css("background-color", "#f0ad4e");
      document.getElementById("id_password1").value = "";
      document.getElementById("id_password2").value = "";

      }

      else if ((ps1.length < min_pass_len) || (ps2.length < min_pass_len)){
        setTimeout(function() {
                    $("#CA_doppleganger").text("Create Account");
                    $("#CA_doppleganger").css("border-color", "#4cae4c");
                    $("#CA_doppleganger").css("background-color", "#5cb85c");
        }, delay);
        $('#CA_doppleganger').text("Password too short");
        $("#CA_doppleganger").css("border-color", "#eea236");
        $("#CA_doppleganger").css("background-color", "#f0ad4e");
        document.getElementById("id_password1").value = "";
        document.getElementById("id_password2").value = "";
      }

      else {
        $("#CA_button").click();
      }
    })
    //password check script
    </script>



    <script type="text/javascript">
    //prevent users from entering the form by pressing 'enter' - due to button doppleganger design
    $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

    </script>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load bootstrap3 %}



{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-sign-in fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}

{% block content_block  %}
<div class="container">

<div class="jumbotron">

  <div class="container">

    {% if user.is_authenticated %}
    <h1 style="text-align:center;">You're already logged in, silly</h1>
    {% else %}
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" name="" value="Login" class="btn btn-success btn-block btn-lg">
    </form>
    <br>
    <a href="{% url 'accounts:signup' %}">Or create an account here</a>
    {% endif %}


</div>
</div>
</div>
{% endblock %}

{% block head_block %}
<style type="text/css">
label[for="id_username"]
{
  display:none;
}
label[for="id_password"]
{
  display:none;
}
</style>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-plus-square-o fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}

{% block content_block  %}
<div class="container">
  <div class="jumbotron">
    <div class="container" id="form_area">

  <form id="formdata" method="post"  data-userIsVal = "null" data-emailIsVal = "null" data-validate-username-url="{% url 'accounts:validate_username' %}" data-validate-email-url="{% url 'accounts:validate_email' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input id="CA_button" type="submit" name="" value="Create Account" class="btn btn-success btn-block btn-lg">
  </form>
  <button id="CA_doppleganger" style="display: none;" type="button" class="btn btn-success btn-lg btn-block" name="button">Create Account</button>
</div>
</div>

</div>
{% endblock %}


{% block head_block %}
<style type="text/css">
label
{
  display:none;
}


.help-block {
  display:none;
}
</style>
{% endblock %}



{% block js_block %}

<script type="text/javascript">
  $("#id_username").change(function () {
    var form = $(this).closest("form");
    $.ajax({
      url: form.attr("data-validate-username-url"),
      data: form.serialize(),
      dataType: 'json',
      success: function (data) {
        if (data.is_taken) {
          $("#id_username").val("");
          $("#id_username").attr("placeholder", "That username is taken");
          $("#id_username").css("border-color", "#ff6666");
          $("#id_username").focus();
          $("#formdata").data("userIsVal", "0");
          }
        else {
          $("#id_username").css("border-color", "#66ff99");
          $("#formdata").data("userIsVal", "1");
          }
        }
      });
    });
  </script>

<script type="text/javascript">
    $("#id_email").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-email-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            $("#id_email").val("");
            $("#id_email").attr("placeholder", "That email address is taken");
            $("#id_email").css("border-color", "#ff6666");
            $("#id_email").focus();
            $("#formdata").data("emailIsVal", "0");
            }
        else {
          $("#id_email").css("border-color", "#66ff99");
          $("#formdata").data("emailIsVal", "1");
          }
        }
    });
  });
</script>


<script type="text/javascript">
  $("#CA_button").css("display", "none");
  $("#CA_doppleganger").css("display", "block");
</script>

<script type="text/javascript">
    $("#CA_doppleganger").on('click', function() {
      var delay=2000; //1 second
      var min_pass_len = 6;
      var ps1 = document.getElementById("id_password1").value;
      var ps2 = document.getElementById("id_password2").value;

      if (ps1 != ps2){
      setTimeout(function() {
                  $("#CA_doppleganger").text("Create Account");
                  $("#CA_doppleganger").css("border-color", "#4cae4c");
                  $("#CA_doppleganger").css("background-color", "#5cb85c");
      }, delay);
      $('#CA_doppleganger').text("Passwords don't match");
      $("#CA_doppleganger").css("border-color", "#eea236");
      $("#CA_doppleganger").css("background-color", "#f0ad4e");
      document.getElementById("id_password1").value = "";
      document.getElementById("id_password2").value = "";

      }

      else if ((ps1.length < min_pass_len) || (ps2.length < min_pass_len)){
        setTimeout(function() {
                    $("#CA_doppleganger").text("Create Account");
                    $("#CA_doppleganger").css("border-color", "#4cae4c");
                    $("#CA_doppleganger").css("background-color", "#5cb85c");
        }, delay);
        $('#CA_doppleganger').text("Password too short");
        $("#CA_doppleganger").css("border-color", "#eea236");
        $("#CA_doppleganger").css("background-color", "#f0ad4e");
        document.getElementById("id_password1").value = "";
        document.getElementById("id_password2").value = "";
      }

      else {
        $("#CA_button").click();
      }
    })
    //password check script
    </script>



    <script type="text/javascript">
    //prevent users from entering the form by pressing 'enter' - due to button doppleganger design
    $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

    </script>

{% endblock %}

accounts/templates/accounts/thanks.html
{% extends 'base.html' %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-meh-o fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}


{% block content_block %}
<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
  <h3 style="font-weight: lighter;">Thanks for visiting, come back soon!</h3>
  </div>
</div>
{% endblock %}