API/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from API import views

app_name = 'api'

urlpatterns = [
    url(r'^$', views.info, name='info'),
    url(r'^core/$', views.core, name='core'),
    url(r'^core/dau/$', views.dau, name='dau'),
    url(r'^remote/$', views.remote, name='rm'),
]

Tricle/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Tricle import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^scrambler/', include('scrambler.urls', namespace='scrambler')),
    url(r'^scrambler/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name='test'),
    url(r'^privacy$', views.PrivacyPage.as_view(), name='privacy'),
    url(r'contact/$', views.ContactPage.as_view(), name='contact'),
    url(r'global/$', views.stats, name='global'),
    url(r'go/$', views.GettingStarted.as_view(), name='go'),
    url(r'about/$', views.AboutPage.as_view(), name='about'),
    url(r'^scrambler/$', views.ScramRedirect),
    url(r'^iaw/$', views.cleanup, name="cleanup"),
    url(r'^api/', include('API.urls', namespace='api')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signup'),
    url(r'^thanks/$', views.ThanksPage, name='thanks'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^ajax/validate_email/$', views.validate_email, name='validate_email'),
]

scrambler/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from scrambler import views

app_name = 'scrambler'

urlpatterns = [
    url(r'^$', views.StartPage, name='start'),
    url(r'^account/$', views.AccountPage, name='account'),
    url(r'^(?P<hash>\w+)/$', views.load_url, name="url"),
    url(r'^down/(?P<hash>\w+)/$', views.download_url, name="down"),
    url(r'^done/(?P<hash>\w+)/$', views.done_url, name="done"),
]

templates/about.html
{% extends 'base.html' %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-question fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}


{% block content_block %}

<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
  <h3 style="font-weight: lighter;">Want to know more?</h3>
  </div>
</div>

<div class="container">
  <div class="jumbotron">


    <p>Tricle develops web apps for enhancing privacy.</p>
    <ul>


    <li>The Scrambler is a program which takes an image and uses an algorithm to 'scramble' the pixels. This effectively encryptions the image and is used as
     a form of encryption. While the algorithm is secure, it shouldn't be used exclusively. Actual encryption technologies are required for full privacy; this algorithm
   is just an additional layer of security. In scrambled images, you may notice little squares. These are a misdirection, and even if someone tries put them back together, they
 won't successfully recreate the image.</li>

<br>

   <li>There are currently a few more web apps and an Android app in development. One web app uses the Scrambler algorithm to hide additional information within images
   and has had some promising results. The android app uses true encryption technologies but in a novel way (hopefully).</li>

<br>

   <li>To use the tools, an account is required. An account is free to create and only requires a username, an email address, and a password. The account allows us to
   keep track of how much the tool is being used without invasive tracking tools and cookies.</li>
</ul>

    </div>
</div>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-envelope fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}


{% block content_block %}

<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
  <h3 style="font-weight: lighter;">Want to chat?</h3>
  </div>
</div>



<div class="container">
  <div class="row">
    <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
      <a href="https://wwww.fb.me/triclexyz" style="text-decorations: none;">
      <div class="facebook" style="padding-top:20px; padding-bottom:20px;">
          <h1 style="text-align: center; color:#3b5998;"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></h1>
      </div>
    </a>

    </div>
    <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
      <div class="twitter" style="padding-top:20px; padding-bottom:20px;">
        <h1 style="text-align: center;color:  #1da1f2;"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></h1>
      </div>
    </div>

    <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
      <div class="email" style="padding-top:20px; padding-bottom:20px;">
      <h1 style="text-align: center;color:  #ea4335;"><i class="fa fa-envelope-o fa-2x" aria-hidden="true"></i></h1>
      </div>
    </div>
  </div>

</div>
{% endblock %}

templates/getstarted.html
{% extends 'base.html' %}

{% block icon_block %}
<div class="container">
  <div class="jumbotron tophead">
    <h1 style="text-align: center;"><i class="fa fa-play-circle fa-2x" aria-hidden="true"></i></h1>
  </div>
</div>
{% endblock %}


{% block content_block %}
<div class="container">
  <div class="jumbotron" style="background-color: #EFF7F6; text-align: center;">
  <h3 style="font-weight: lighter;">Get Started</h3>
  </div>
</div>

<div class="container">
  <div class="jumbotron">
    <ul>

    <li>Once you have logged in, on the Start page you'll be shown a form asking for three keys, the images you want to scramble, and whether you want to scramble or unscramble</li>
<br>
    <li>The order of your keys is important and must be remembered. The keys can be whatever you want, but try not to make them too obvious</li>
<br>
    <li>The keys are case-sensitive, should be at least three characters long, and shouldn't contain whitespace</li>
<br>
    <li>Select the bmp/jpeg images that you want to hide, select scramble, and click start</li>
<br>
    <li>Or if you want to unhide some images, select unscramble</li>
<br>
    <li>You'll be redirected to a download page. The download should start automatically, but if it doesn't, click the download button</li>
<br>
    <li>Once you have downloaded your processed files, click the blue button, which will remove any temporary files left on our servers</li>

    </ul>
  </div>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Free web apps to enhance your privacy">
    <title>Tricle</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{%  static 'icons/favicon-lock.ico' %}">



    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    <!--<![endif]-->

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

        <!--[if lte IE 8]>
            <link rel="stylesheet" href=" {% static 'css/pure-ie.css' %}">
        <![endif]-->
        <!--[if gt IE 8]><!-->
            <link rel="stylesheet" href=" {% static 'css/pure.css' %}">
        <!--<![endif]-->
</head>
<body>









<div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'home' %}">Tricle</a>

        <ul class="pure-menu-list">
          {% if user.is_authenticated %}
            <li class="pure-menu-item"><a href="{% url 'home' %}#apps" class="pure-menu-link">Apps</a></li>
            <li class="pure-menu-item"><a href="{% url 'scrambler:account' %}" class="pure-menu-link">Account</a></li>
            <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Logout</a></li>
            {% else %}
            <li class="pure-menu-item"><a href="{% url 'home' %}#apps" class="pure-menu-link">Apps</a></li>
            <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Log In</a></li>
            <li class="pure-menu-item"><a href="{% url 'accounts:signup' %}" class="pure-menu-link">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</div>

<div class="splash-container" style="
	background-image: url('/static/images/new.jpg');
	background-position: centre; background-size:cover;">
    <div class="splash" style="color: #343434 !important;">
        <h1 class="splash-head" style="color: #2d3e50 !important; border-color: #2d3e50 !important;">Welcome to Tricle</h1>
        <p class="splash-subhead" style="color: #2d3e50 !important;">
            Free web apps to enhance your privacy
        </p>
    </div>
</div>

<div class="content-wrapper">
    <div class="content">
        <h2 class="content-head is-center">Our apps are</h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">

                <h3 class="content-subhead">
                    <i class="fa fa-rocket"></i>
                   Free
                </h3>
                <p>
                    Create an account with nothing but a username, email address and password
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
                <h3 class="content-subhead">
                    <i class="fa fa-lock"></i>
                    Secure
                </h3>
                <p>
                    We value your privacy, we do not keep your files
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-3">
                <h3 class="content-subhead">
                    <i class="fa fa-bolt"></i>
                    Quick
                </h3>
                <p>
                    Our apps are as quick as the algorithms allow, which we are continuously optimising
                </p>
            </div>
        </div>
    </div>

    <a name="apps"></a>

    <div  class="ribbon l-box-lrg pure-g">

        <div class="pure-u-1 pure-u-md-1 pure-u-lg-1">

            <h2 class="content-head content-head-ribbon" style="text-align:center;">Scrambler</h2>

            <h4 style="text-align:center; color: white;">
               Hide your valuable images, using any device, for free.
			</h4>
			<p>
				The scrambler take three keys and uses an algorithm to scramble the pixels
				in your image in a reversable way. This allows you to hide your images,
				which are effectively encrypted with a one-pad cither.
            </p>
            <br>
			<div  style="text-align:center;"><a class="pure-button pure-button-primary" href="{% url 'scrambler:start' %}">Start Scrambling</a>
			</div>
        </div>
    </div>


	<div class="content l-box-lrg pure-g">

        <div class="pure-u-1 pure-u-md-1 pure-u-lg-1">

            <h2 class="content-head" style="text-align:center;">Hider</h2>

            <h4 style="text-align:center;">
               Hide short messages within images.
			</h4>
			<p>
				Built on the scrambler algorithm, this app allows you to hide multiple small messages within
				   images using different passwords for each message within the same image.
            </p>
            <br>
			<div  style="text-align:center;"><a class="pure-button pure-button-primary" disabled>In development</a>
			</div>
        </div>
    </div>

	<div class="ribbon l-box-lrg pure-g">

        <div class="pure-u-1 pure-u-md-1 pure-u-lg-1">

            <h2 class="content-head content-head-ribbon" style="text-align:center;">Path</h2>

            <h4 style="text-align:center; color:white;">
               A fresh way to encrypt files on Android
			</h4>
			<p>
			Typical encryption apps use passwords and patterns to generate encryption keys. Path uses procedurally generated patterns
			that allow for a greater level of security.
            </p>
            <br>
			<div  style="text-align:center;"><a class="pure-button pure-button-primary" disabled>In development</a>
			</div>
        </div>
    </div>








<footer>
<div class="container text-center">
<br>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'about' %}">About us</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'go' %}">Getting Started</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="https://imgur.com/a/QcMTV" >Examples</a></li>
        </ul>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'global' %}">Analytics</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'contact' %}">Contact Us</a></li>
        </ul>
      </div>
      <div class="col-md-4">

        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'privacy' %}">Privacy</a></li>
        </ul>
      </div>
    </div>
  </div>

<hr>

<p style="text-align: center;">&copy Tricle 2017</p>

</div>
<br>

</footer>

</div>

<script type="text/javascript" src="{% static 'tricle/js/jscheck.js' %}"></script>

{% block js_block %}

{% endblock %}




</body>
</html>

templates/index2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Hide your images in plain sight for free">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href="{%  static 'icons/favicon-lock.ico' %}">
{% block head_block%}

{% endblock %}

    <!-- Color the status bar on mobile devices -->

    <meta name="theme-color" content="#000000">

	<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link rel="stylesheet" href=" {% static 'css/master.css' %}">


<title>Tricle</title>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-101978839-1', 'auto');
  ga('send', 'pageview');

</script>

<style media="screen">
  .header {
    background-image: url("{% static 'images/head.jpg' %}");
    background-size: cover;
    background-position: center;
    height: 100%;
  }

  .header2 {
    background-color: #333333;
    height: 100%;
  }

  .col{
    color: #86a59c;
  }
</style>
</head>
<body id="content">

<nav class="navbar navbar-inverse" style="border-radius:0; margin-bottom: 0px;">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'home' %}"><span id="wel">Welcome to </span><strong>Tricle</strong></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'scrambler:start' %}">Start</a></li>
          <li><a href="{% url 'scrambler:account' %}">Account</a></li>
          <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
        <li><a href="{% url 'accounts:signup' %}">Create Account</a></li>
        {% endif %}
      </ul>
  </div>
</nav>




<div class="header2" style="padding: 20px;">

<h1 class="col">Tricle</h1>
<p class="col">Your images, hidden.</p>




</div>

<h1>Free forever</h1>
<h1>On all devices</h1>
<h1>Hide your valuable images</h1>

<p>We live in a digital world, a connected world, a world where our privacy is constantly under threat. Tricle develops free tools for enhancing your privacy</p>


<div class="container"  id="jsalert">
<div class="alert alert-danger">
  <strong>Attention!</strong> Please enable JavaScript for full functionality.
</div>
</div>

<div class="container"  id="jsalert">
<div class="alert alert-info">
  <strong>This site is in early alpha</strong> - Some content and functionality is yet to be added.
</div>
</div>


{% if user.is_authenticated %}

<div class="container">
	<div class="jumbotron" style="background-color: #EFF7F6;">

<a style="text-decoration: none" href="{% url 'scrambler:start' %}"><button type="button" class="btn btn-success navbar-btn btn-block btn-lg">Start Scrambling</button></a>
<a style="text-decoration: none" href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-warning navbar-btn btn-block btn-lg">Logout</button></a>
</div>
</div>
{% else %}
<div class="container">
	<div class="jumbotron" style="background-color: #EFF7F6;">

<a style="text-decoration: none" href="{% url 'accounts:login' %}"><button type="button" class="btn btn-success navbar-btn btn-block btn-lg">Login</button></a>
<a style="text-decoration: none" href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-primary navbar-btn btn-block btn-lg">Create Account</button></a>
</div>
</div>
{% endif %}




<script type="text/javascript" src="{% static 'tricle/js/jscheck.js' %}"></script>


</body>

</html>

templates/indexs.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Hide your images in plain sight for free">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href="{%  static 'icons/favicon-lock.ico' %}">


    <!-- Color the status bar on mobile devices -->

    <meta name="theme-color" content="#000000">

	<script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<link rel="stylesheet" href=" {% static 'css/master.css' %}">


<title>Tricle</title>

</head>
<body id="content">

<nav class="navbar navbar-inverse" style="border-bottom-right-radius:0; border-bottom-left-radius: 0; margin-bottom:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'home' %}"><span id="wel">Welcome to </span><strong>Tricle</strong></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'scrambler:start' %}">Start</a></li>
          <li><a href="{% url 'scrambler:account' %}">Account</a></li>
          <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Log In</a></li>
        <li><a href="{% url 'accounts:signup' %}">Create Account</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>




<div class="container"  id="jsalert">
<div class="alert alert-danger">
  <strong>Attention!</strong> Please enable JavaScript for full functionality.
</div>
</div>

<div class="indhead" style="margin-top:0px;">
<h1 style="text-align: center; opacity:0;"><i class="fa fa-lock fa-2x" aria-hidden="true"></i></h1>
</div>



<div class="container"  id="jsalert">
<div class="alert alert-success">
We live in a digital world, a connected world, a world where our privacy is constantly under threat. Tricle develops free tools for enhancing your privacy.
</div>
</div>



<div class="container">

<div class="row">

  <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
    <div class="diamond" style="padding-top:20px; padding-bottom:20px; text-align:center;">
        <h1 style="text-align: center;"><i class="fa fa-diamond fa-2x" aria-hidden="true"></i></h1>
    </div>
  </div>


  <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
    <div class="devices" style="padding-top:20px; padding-bottom:20px; text-align:center;">
      <h1>
      <span>
        <i style="margin:3px;" class="fa fa-mobile fa-1x" aria-hidden="true"></i>
        <i style="margin:3px;" class="fa fa-desktop fa-2x" aria-hidden="true"></i>
        <i style="margin:3px;" class="fa fa-tablet fa-1x" aria-hidden="true"></i>
       </span>
      </h1>
    </div>
  </div>

  <div class="col-xs-4" style="margin-top:10px; margin-bottom:10px;">
    <div class="free" style="padding-top:20px; padding-bottom:20px; text-align:center;">
    <h1 style="text-align: center;"><i class="fa fa-ban fa-2x" aria-hidden="true"></i></h1>
    </div>
  </div>



</div>

<p style="text-align:center;">Hide your valuable images, using any device, for free.</p>


<hr>
<div class="container">


<p>The scrambler take three keys and uses an algorithm to scramble the pixels in your
image in a reversable way. This allows you to hide your images, which are effectively
encrypted with a one-pad cither.</p>

</div>
</div>


<style media="screen">
  .infobox{
    background-color: #333333;
  }
</style>

<footer class="footer">
<div class="container text-center">

  <br><br><br><br>
    <hr>

  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'about' %}">About us</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'go' %}">Getting Started</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
      <div class="col-md-4">

        <ul class="nav nav-pills nav-stacked">
          <li><a href="https://imgur.com/a/QcMTV" >Examples</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'global' %}">Analytics</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'contact' %}">Contact Us</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
      <div class="col-md-4">

        <ul class="nav nav-pills nav-stacked">
          <li><a href="{% url 'privacy' %}">Privacy</a></li>
          <!--<li><a href="#">Blog</a></li>-->
        </ul>
      </div>
    </div>
  </div>

<hr>

<p style="text-align: center;">&copy Tricle 2017</p>

</div>
<br>

</footer>
<script type="text/javascript" src="{% static 'tricle/js/jscheck.js' %}"></script>

</body>

</html>